### ISSUE TITLE
add_callback parameter 문의

### ISSUE THREAD

**Issue by poopki2018** [wakscord/afreeca#2]
안녕하세요.

![image](https://github.com/user-attachments/assets/ec89b5be-c907-4ce5-aef5-eba5e9cb7567)

예제 코드에서 add_callback함수의 parameter가 적합하지 않아 문의드립니다.

우선 위 사진과 같이 에러가 발생하여, add_callback의 parameter을 확인해보니 string type event도 있어 아래와 같이 추가를 하였는데 적합한 방법인지 문의드립니다.

chat.add_callback("chat",callback)

**Comment by minibox24** [comment]
네! 해당 방식이 맞습니다
리드미를 업데이트하지 않았네요

현재 가능한 callback는 `all`, `chat` 로 두 종류가 있습니다

**Comment by poopki2018** [comment]
확인 감사합니다! 혹시 all으로는 어떤 타입의 이벤트를 받는지 알 수 있을까요?

chat callback으로는 채팅만 받고, all은 모든 이벤트(별풍선, 구독 등)을 받는건지 확인 부탁드립니다!

**Comment by minibox24** [comment]
네 맞습니다.

all 이벤트의 경우에는 이벤트 아이디와 raw packet을 전달해서 관련 기능을 직접 구현하셔야 합니다.

**Comment by poopki2018** [comment]
확인 감사합니다!! 좋은 라이브러리 너무나도 감사합니다!
